ALTER PROCEDURE dbo.UpdateEmployeeSP 
	@EMPLOYEEID INT,
	@FRISTNAME NVARCHAR(20), 
	@LASTNAME NVARCHAR(20),
	@EMAIL NVARCHAR(40),
	@MOBLILENUMBER NVARCHAR(20),
	@CV NVARCHAR(50),
	@EADDRESS NVARCHAR(50),
	@BIRTHDATE DATE,
	@JOINDATE DATE,
	@RESIGNDATE DATE,
	@USERID INT,
	@Gender VARCHAR(20)
AS   
BEGIN
	DECLARE @ERROR AS VARCHAR(MAX) =''
	DECLARE @TOTAL_EMAIL AS INT =0
	DECLARE @TOTAL_MOBILE AS INT =0
	
	
	SELECT @TOTAL_EMAIL = COUNT(@Email) FROM Employee WHERE Email=@Email
	
	IF(@TOTAL_EMAIL>1)
	BEGIN
		SET @ERROR += 'Email is already exist.'
	END
	ELSE IF (@TOTAL_EMAIL = 1 AND (SELECT Email FROM Employee WHERE EMPLOYEEID = @EMPLOYEEID) != @EMAIL)
	BEGIN
		SET @ERROR += 'Enter a New Email Or Previous One.'		
	END

	SELECT  @TOTAL_MOBILE = COUNT(@MOBLILENUMBER) FROM Employee WHERE MoblileNumber = @MOBLILENUMBER
	
	IF( @TOTAL_MOBILE>1)
	BEGIN
		SET @ERROR += 'Moblile Number is already exist.'
	END
	ELSE IF (@TOTAL_MOBILE = 1 AND (SELECT MoblileNumber FROM Employee WHERE EMPLOYEEID = @EMPLOYEEID) != @MOBLILENUMBER)
	BEGIN
		SET @ERROR += 'Enter a New Moblile Number Or Previous One.'		
	END

	IF(@ERROR = '')
	BEGIN
		UPDATE EMPLOYEE SET 
		FRISTNAME = @FRISTNAME, 
		LASTNAME = @LASTNAME,
		EMAIL = @EMAIL,
		MOBLILENUMBER = @MOBLILENUMBER,
		CV = @CV,
		EADDRESS = @EADDRESS,
		BIRTHDATE = @BIRTHDATE,
		JOINDATE = @JOINDATE,
		RESIGNDATE = @RESIGNDATE,
		USERID = @USERID,
		Gender = @Gender
		WHERE EMPLOYEEID = @EMPLOYEEID
		SELECT @ERROR AS ErrorMessage
	END
	ELSE
		SELECT @ERROR AS ErrorMessage
END